spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true # 强制开启UTF8编码
      charset: UTF-8
      enabled: true

server:
  tomcat: 
    uri-encoding: UTF-8

#logging:
#  config: classpath:logback-spring.xml
#  level:
#    dao: debug
#    org:
#      mybatis: debug